# Generated by Django 5.2.6 on 2025-09-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Something",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("something_from_another_service", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
