# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: something.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'something.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fsomething.proto\x12\tsomething\"U\n\x10SomethingMessage\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12&\n\x1esomething_from_another_service\x18\x03 \x01(\t\"I\n\x17ProcessSomethingRequest\x12.\n\tsomething\x18\x01 \x01(\x0b\x32\x1b.something.SomethingMessage\"J\n\x18ProcessSomethingResponse\x12.\n\tsomething\x18\x01 \x01(\x0b\x32\x1b.something.SomethingMessage2q\n\x12SomethingProcessor\x12[\n\x10ProcessSomething\x12\".something.ProcessSomethingRequest\x1a#.something.ProcessSomethingResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'something_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SOMETHINGMESSAGE']._serialized_start=30
  _globals['_SOMETHINGMESSAGE']._serialized_end=115
  _globals['_PROCESSSOMETHINGREQUEST']._serialized_start=117
  _globals['_PROCESSSOMETHINGREQUEST']._serialized_end=190
  _globals['_PROCESSSOMETHINGRESPONSE']._serialized_start=192
  _globals['_PROCESSSOMETHINGRESPONSE']._serialized_end=266
  _globals['_SOMETHINGPROCESSOR']._serialized_start=268
  _globals['_SOMETHINGPROCESSOR']._serialized_end=381
# @@protoc_insertion_point(module_scope)
